from typing import Tuple, List

def clear(port: int) -> None: ...
def get_pixel(port: int, x: int, y: int) -> Tuple[int, int]: ...
def set_pixel(port: int, x: int, y: int, pixel: Tuple[int, int]) -> None: ...
def show(port: int, pixels: List[Tuple[int, int]]) -> None: ...
