
from typing import Tuple
"""Color Sensor procedural API."""
def color(port: int) -> int:
    """Return a color constant detected at *port* (see `color` module).""" ...
def reflection(port: int) -> int:
    """Return reflected light intensity at *port* as a percentage (0..100).""" ...
def rgbi(port: int) -> Tuple[int, int, int, int]:
    """Return raw (R, G, B, illuminance) readings from *port*.""" ...
