
from typing import Tuple
"""Generic device IO helpers for advanced usage (subset)."""
def data(port: int) -> Tuple[int, ...]:
    """Return a tuple of raw data values from the device at *port*.""" ...
def id(port: int) -> int:
    """Return the device type identifier present at *port*.""" ...
def get_duty_cycle(port: int) -> int:
    """Return the current PWM duty cycle (-100..100) applied to *port*.""" ...
def ready(port: int) -> bool:
    """Return True if the device on *port* is ready/connected.""" ...
def set_duty_cycle(port: int, duty_cycle: int) -> None:
    """Set raw PWM duty cycle (-100..100) on *port*.""" ...
