from typing import Tuple
def data(port: int) -> Tuple[int, ...]: ...
def id(port: int) -> int: ...
def get_duty_cycle(port: int) -> int: ...
def ready(port: int) -> bool: ...
def set_duty_cycle(port: int, duty_cycle: int) -> None: ...
