
def distance(p: object) -> int:
    """Return measured distance (typ. mm or cm depending on environment).""" ...

def presence(p: object) -> int:
    """Return 1 if an object is detected in front of the sensor, else 0.""" ...

def ambient(p: object) -> int:
    """Return ambient light intensity as measured by the distance sensor.""" ...

def light(p: object) -> int:
    """Return reflected light intensity from the distance sensor emitter.""" ...
