
"""Force Sensor procedural API."""
def force(port: int) -> int:
    """Return measured force/pressure value on *port*.""" ...
def pressed(port: int) -> bool:
    """Return True if the force sensor at *port* is pressed; otherwise False.""" ...
def raw(port: int) -> int:
    """Return raw ADC reading from the sensor at *port*.""" ...
