
from typing import Awaitable, Callable, Any
"""Async run loop used by SPIKE 3's awaitable APIs (motors, music, etc.)."""
def run(coro: Callable[[], Awaitable[Any]]) -> None:
    """Run the top-level async *coro* until completion.""" ...
def sleep(ms: int) -> Awaitable[None]:
    """Awaitable sleep for *ms* milliseconds (non-blocking).""" ...
def sleep_ms(ms: int) -> Awaitable[None]:
    """Alias of ``sleep``; awaitable delay for *ms* milliseconds.""" ...
def until(pred: Callable[[], bool]) -> Awaitable[None]:
    """Await until *pred()* returns True; checks predicate periodically without blocking the hub.""" ...
