from typing import Awaitable, Callable, Any

def run(coro: Callable[[], Awaitable[Any]]) -> None: ...
def sleep(ms: int) -> Awaitable[None]: ...
def sleep_ms(ms: int) -> Awaitable[None]: ...
def until(pred: Callable[[], bool]) -> Awaitable[None]: ...
