
"""Hub status light control."""
def on(color: int) -> None:
    """Turn the hub **status** light on to the given *color* constant (see `color`).""" ...
def off() -> None:
    """Turn the hub **status** light off.""" ...
