
"""MicroPython binascii subset (binary/text conversions)."""
def hexlify(data: bytes) -> bytes:
    """Return hexadecimal representation of *data* (lowercase, no separators).""" ...
def unhexlify(data: bytes) -> bytes:
    """Return binary data decoded from hexadecimal string *data*.""" ...
def b2a_base64(data: bytes) -> bytes:
    """Return base64-encoded *data* as bytes (may include newline).""" ...
def a2b_base64(data: bytes) -> bytes:
    """Return binary data decoded from base64-encoded *data*.""" ...
