
def hexlify(data: bytes) -> bytes:
    """Return hexadecimal representation of *data*.""" ...
def unhexlify(data: bytes) -> bytes:
    """Inverse of hexlify: convert hex to binary.""" ...
def b2a_base64(data: bytes) -> bytes:
    """Base64-encode *data* returning a bytes result (may include newline).""" ...
def a2b_base64(data: bytes) -> bytes:
    """Decode base64-encoded *data* to bytes.""" ...
