
class StringIO:
    """In-memory text stream (subset of CPython io.StringIO)."""
    def __init__(self, s: str = ...) -> None: ...
    def write(self, s: str) -> int: ...
    def read(self, n: int = ...) -> str: ...
    def readline(self) -> str: ...
    def seek(self, pos: int, whence: int = ...) -> None: ...
    def getvalue(self) -> str: ...
