
"""MicroPython in-memory text stream subset."""
class StringIO:
    """Minimal StringIO compatible with MicroPython usage."""
    def __init__(self, s: str = ...) -> None: ...
    def write(self, s: str) -> int:
        """Write string *s* and return number of characters written.""" ...
    def read(self, n: int = ...) -> str:
        """Read up to *n* characters (or all if omitted) and return them.""" ...
    def readline(self) -> str:
        """Read one line (terminated by newline) and return it.""" ...
    def seek(self, pos: int, whence: int = ...) -> None:
        """Move the file position to *pos* (with optional *whence*).""" ...
    def getvalue(self) -> str:
        """Return the entire contents as a string.""" ...
