
from typing import List, Tuple, Iterable
"""MicroPython OS/filesystem subset."""
def uname() -> Tuple[str, ...]:
    """Return a tuple of system information fields (implementation-defined).""" ...
def ilistdir(path: str = '.') -> Iterable[Tuple[int, str]]:
    """Iterate directory entries at *path*, yielding (type, name).""" ...
def listdir(path: str = '.') -> List[str]:
    """Return a list of entries in directory *path* (default current).""" ...
def mkdir(path: str) -> None:
    """Create a directory at *path*.""" ...
def remove(path: str) -> None:
    """Remove (unlink) file at *path*.""" ...
def rename(old: str, new: str) -> None:
    """Rename a file or directory from *old* to *new*.""" ...
def rmdir(path: str) -> None:
    """Remove an empty directory at *path*.""" ...
def stat(path: str) -> Tuple[int, ...]:
    """Return a tuple with stat info for *path* (mode, size, times, etc.).""" ...
def getcwd() -> str:
    """Return the current working directory path.""" ...
def chdir(path: str) -> None:
    """Change the current working directory to *path*.""" ...
