
from typing import List

def uname() -> tuple:
    """Return system information tuple (implementation-defined).""" ...
def listdir(path: str = ...) -> List[str]:
    """List directory entries at *path* (default current).""" ...
def mkdir(path: str) -> None:
    """Create a directory at *path*.""" ...
def remove(path: str) -> None:
    """Remove a file at *path*.""" ...
def rmdir(path: str) -> None:
    """Remove an empty directory at *path*.""" ...
def stat(path: str) -> tuple:
    """Return stat info for *path* (mode, size, times, etc.).""" ...
def getcwd() -> str:
    """Return current working directory.""" ...
def chdir(path: str) -> None:
    """Change current working directory to *path*.""" ...
