
"""MicroPython random subset."""
def getrandbits(n: int) -> int:
    """Return an integer with *n* random bits (0 <= x < 2**n).""" ...
def randint(a: int, b: int) -> int:
    """Return random integer N such that a <= N <= b.""" ...
def seed(n: int = ...) -> None:
    """Seed the pseudo-random number generator with *n*.""" ...
