
def getrandbits(n: int) -> int:
    """Return an integer with *n* random bits.""" ...
def randint(a: int, b: int) -> int:
    """Return random integer N such that a <= N <= b.""" ...
def seed(n: int = ...) -> None:
    """Seed the PRNG with *n* (implementation-dependent).""" ...
